-- Database: plant_sim_db
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS testing;

DROP SCHEMA IF EXISTS analytics CASCADE;
DROP SCHEMA IF EXISTS staging CASCADE;
DROP SCHEMA IF EXISTS testing CASCADE;

CREATE SCHEMA analytics;
CREATE SCHEMA staging;
CREATE SCHEMA testing;

SET search_path TO analytics;

CREATE TABLE dim_scenario (
    scenario_id 			TEXT PRIMARY KEY,
    scenario_name 			TEXT NOT NULL,
	
    interarrival_mean_sec 	NUMERIC NOT NULL,
    wip_limit 				INT NOT NULL,
    wip_poll_interval 		INT NOT NULL,
    sim_horizon_days 		INT NOT NULL,
	
    created_at 				TIMESTAMP DEFAULT NOW()
);

CREATE TABLE dim_machine (
    machine_id          INT GENERATED BY DEFAULT AS IDENTITY,
    machine_type        TEXT NOT NULL,
    ideal_cycle_time    INT NOT NULL,
    install_date        DATE NOT NULL,

	scenario_id			TEXT NOT NULL REFERENCES dim_scenario(scenario_id),
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (machine_id, scenario_id)
);

CREATE TABLE dim_product (
    product_id          INT GENERATED BY DEFAULT AS IDENTITY,
    product_name        TEXT NOT NULL,
    product_family      TEXT NOT NULL,
    
	target_yield_rate   NUMERIC(5,4) NOT NULL,
    sample_per_yield    NUMERIC(4, 2) NOT NULL,

	scenario_id			TEXT NOT NULL REFERENCES dim_scenario(scenario_id),
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (product_id, scenario_id)
);

CREATE TABLE dim_process (
    process_id      INT GENERATED BY DEFAULT AS IDENTITY,
    process_name    TEXT NOT NULL,
    product_id      INT NOT NULL,

	scenario_id		TEXT NOT NULL,
	created_at      TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (process_id, scenario_id),
	
	FOREIGN KEY (product_id, scenario_id)
		REFERENCES dim_product(product_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE dim_process_route (
    process_route_id    INT GENERATED BY DEFAULT AS IDENTITY,
    process_id          INT NOT NULL,
    step_number         INT NOT NULL,
    
	machine_type        TEXT NOT NULL,
	step_cycle_time     INT NOT NULL,

	scenario_id			TEXT NOT NULL,
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (process_route_id, scenario_id),

	FOREIGN KEY (process_id, scenario_id)
		REFERENCES	dim_process(process_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_work_order (
    work_order_id       	TEXT NOT NULL,
    product_id          	INT NOT NULL,
    
	planned_quantity    	INT NOT NULL,
    target_yield_rate   	NUMERIC(5,4),
    batch_size          	INT NOT NULL,
    
	start_date          	DATE NOT NULL,
    due_date            	DATE NOT NULL,
	priority            	INT NOT NULL,

	work_order_start_time	NUMERIC NOT NULL,
	work_order_end_time		NUMERIC NOT NULL,

	scenario_id				TEXT NOT NULL,
	created_at          	TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (work_order_id, scenario_id),

	FOREIGN KEY (product_id, scenario_id)
		REFERENCES dim_product(product_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_production_event (
    event_id            INT GENERATED BY DEFAULT AS IDENTITY,
    work_order_id       TEXT NOT NULL,
    
	machine_id          INT NOT NULL,
    process_id    		INT NOT NULL,
	process_route_id	INT NOT NULL,
    step_number         INT NOT NULL,

	batch_id            INT GENERATED BY DEFAULT AS IDENTITY,
	
	process_start       NUMERIC NOT NULL,
    process_end         NUMERIC NOT NULL,

	ideal_cycle_time    INT NOT NULL,	
    actual_cycle_time   NUMERIC NOT NULL,
    
	event_status        TEXT NOT NULL,

	scenario_id			TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (event_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id),
		
	UNIQUE (batch_id, scenario_id)
);

CREATE TABLE fact_downtime_event (
    downtime_id         INT GENERATED BY DEFAULT AS IDENTITY,
    
	work_order_id 		TEXT NOT NULL,
	process_id			INT NOT NULL,
	process_route_id	INT NOT NULL,
	machine_id          INT NOT NULL,
    
	failure_type        TEXT NOT NULL,
    
	usage_duration      NUMERIC NOT NULL,
    failure_start       NUMERIC NOT NULL,
    failure_end         NUMERIC NOT NULL,

	scenario_id			TEXT NOT NULL,
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (downtime_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_quality_event (
    quality_id          INT GENERATED BY DEFAULT AS IDENTITY,
    
	work_order_id       TEXT NOT NULL,
	machine_id          INT NOT NULL,
	process_id			INT NOT NULL,
    process_route_id    INT NOT NULL,
    step_number         INT NOT NULL,
	
	batch_id            INT NOT NULL,
    
	initial_quantity    INT NOT NULL,
	units_approved      INT NOT NULL,
    units_scrapped      INT NOT NULL,

	event_time          NUMERIC NOT NULL,

	scenario_id			TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (quality_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
	-- Future extension: defect_type, severity
);

SET search_path TO staging;

CREATE TABLE dim_scenario (
    scenario_id 			TEXT PRIMARY KEY,
    scenario_name 			TEXT NOT NULL,
	
    interarrival_mean_sec 	NUMERIC NOT NULL,
    wip_limit 				INT NOT NULL,
    wip_poll_interval 		INT NOT NULL,
    sim_horizon_days 		INT NOT NULL,
	
    created_at 				TIMESTAMP DEFAULT NOW()
);

CREATE TABLE dim_machine (
    machine_id          INT GENERATED BY DEFAULT AS IDENTITY,
    machine_type        TEXT NOT NULL,
    ideal_cycle_time    INT NOT NULL,
    install_date        DATE NOT NULL,

	scenario_id			TEXT NOT NULL REFERENCES dim_scenario(scenario_id),
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (machine_id, scenario_id)
);

CREATE TABLE dim_product (
    product_id          INT GENERATED BY DEFAULT AS IDENTITY,
    product_name        TEXT NOT NULL,
    product_family      TEXT NOT NULL,
    
	target_yield_rate   NUMERIC(5,4) NOT NULL,
    sample_per_yield    NUMERIC(4, 2) NOT NULL,

	scenario_id			TEXT NOT NULL REFERENCES dim_scenario(scenario_id),
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (product_id, scenario_id)
);

CREATE TABLE dim_process (
    process_id      INT GENERATED BY DEFAULT AS IDENTITY,
    process_name    TEXT NOT NULL,
    product_id      INT NOT NULL,

	scenario_id		TEXT NOT NULL,
	created_at      TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (process_id, scenario_id),
	
	FOREIGN KEY (product_id, scenario_id)
		REFERENCES dim_product(product_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE dim_process_route (
    process_route_id    INT GENERATED BY DEFAULT AS IDENTITY,
    process_id          INT NOT NULL,
    step_number         INT NOT NULL,
    
	machine_type        TEXT NOT NULL,
	step_cycle_time     INT NOT NULL,

	scenario_id			TEXT NOT NULL,
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (process_route_id, scenario_id),

	FOREIGN KEY (process_id, scenario_id)
		REFERENCES	dim_process(process_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_work_order (
    work_order_id       	TEXT NOT NULL,
    product_id          	INT NOT NULL,
    
	planned_quantity    	INT NOT NULL,
    target_yield_rate   	NUMERIC(5,4),
    batch_size          	INT NOT NULL,
    
	start_date          	DATE NOT NULL,
    due_date            	DATE NOT NULL,
	priority            	INT NOT NULL,

	work_order_start_time	NUMERIC NOT NULL,
	work_order_end_time		NUMERIC NOT NULL,

	scenario_id				TEXT NOT NULL,
	created_at          	TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (work_order_id, scenario_id),

	FOREIGN KEY (product_id, scenario_id)
		REFERENCES dim_product(product_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_production_event (
    event_id            INT GENERATED BY DEFAULT AS IDENTITY,
    work_order_id       TEXT NOT NULL,
    
	machine_id          INT NOT NULL,
    process_id    		INT NOT NULL,
	process_route_id	INT NOT NULL,
    step_number         INT NOT NULL,

	batch_id            INT GENERATED BY DEFAULT AS IDENTITY,
	
	process_start       NUMERIC NOT NULL,
    process_end         NUMERIC NOT NULL,

	ideal_cycle_time    INT NOT NULL,	
    actual_cycle_time   NUMERIC NOT NULL,
    
	event_status        TEXT NOT NULL,

	scenario_id			TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (event_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id),
		
	UNIQUE (batch_id, scenario_id)
);

CREATE TABLE fact_downtime_event (
    downtime_id         INT GENERATED BY DEFAULT AS IDENTITY,
    
	work_order_id 		TEXT NOT NULL,
	process_id			INT NOT NULL,
	process_route_id	INT NOT NULL,
	machine_id          INT NOT NULL,
    
	failure_type        TEXT NOT NULL,
    
	usage_duration      NUMERIC NOT NULL,
    failure_start       NUMERIC NOT NULL,
    failure_end         NUMERIC NOT NULL,

	scenario_id			TEXT NOT NULL,
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (downtime_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_quality_event (
    quality_id          INT GENERATED BY DEFAULT AS IDENTITY,
    
	work_order_id       TEXT NOT NULL,
	machine_id          INT NOT NULL,
	process_id			INT NOT NULL,
    process_route_id    INT NOT NULL,
    step_number         INT NOT NULL,
	
	batch_id            INT NOT NULL,
    
	initial_quantity    INT NOT NULL,
	units_approved      INT NOT NULL,
    units_scrapped      INT NOT NULL,

	event_time          NUMERIC NOT NULL,

	scenario_id			TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (quality_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
	-- Future extension: defect_type, severity
);

SET search_path TO testing;

CREATE TABLE dim_scenario (
    scenario_id 			TEXT PRIMARY KEY,
    scenario_name 			TEXT NOT NULL,
	
    interarrival_mean_sec 	NUMERIC NOT NULL,
    wip_limit 				INT NOT NULL,
    wip_poll_interval 		INT NOT NULL,
    sim_horizon_days 		INT NOT NULL,
	
    created_at 				TIMESTAMP DEFAULT NOW()
);

CREATE TABLE dim_machine (
    machine_id          INT GENERATED BY DEFAULT AS IDENTITY,
    machine_type        TEXT NOT NULL,
    ideal_cycle_time    INT NOT NULL,
    install_date        DATE NOT NULL,

	scenario_id			TEXT NOT NULL REFERENCES dim_scenario(scenario_id),
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (machine_id, scenario_id)
);

CREATE TABLE dim_product (
    product_id          INT GENERATED BY DEFAULT AS IDENTITY,
    product_name        TEXT NOT NULL,
    product_family      TEXT NOT NULL,
    
	target_yield_rate   NUMERIC(5,4) NOT NULL,
    sample_per_yield    NUMERIC(4, 2) NOT NULL,

	scenario_id			TEXT NOT NULL REFERENCES dim_scenario(scenario_id),
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (product_id, scenario_id)
);

CREATE TABLE dim_process (
    process_id      INT GENERATED BY DEFAULT AS IDENTITY,
    process_name    TEXT NOT NULL,
    product_id      INT NOT NULL,

	scenario_id		TEXT NOT NULL,
	created_at      TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (process_id, scenario_id),
	
	FOREIGN KEY (product_id, scenario_id)
		REFERENCES dim_product(product_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE dim_process_route (
    process_route_id    INT GENERATED BY DEFAULT AS IDENTITY,
    process_id          INT NOT NULL,
    step_number         INT NOT NULL,
    
	machine_type        TEXT NOT NULL,
	step_cycle_time     INT NOT NULL,

	scenario_id			TEXT NOT NULL,
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (process_route_id, scenario_id),

	FOREIGN KEY (process_id, scenario_id)
		REFERENCES	dim_process(process_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_work_order (
    work_order_id       	TEXT NOT NULL,
    product_id          	INT NOT NULL,
    
	planned_quantity    	INT NOT NULL,
    target_yield_rate   	NUMERIC(5,4),
    batch_size          	INT NOT NULL,
    
	start_date          	DATE NOT NULL,
    due_date            	DATE NOT NULL,
	priority            	INT NOT NULL,

	work_order_start_time	NUMERIC NOT NULL,
	work_order_end_time		NUMERIC NOT NULL,

	scenario_id				TEXT NOT NULL,
	created_at          	TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (work_order_id, scenario_id),

	FOREIGN KEY (product_id, scenario_id)
		REFERENCES dim_product(product_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_production_event (
    event_id            INT GENERATED BY DEFAULT AS IDENTITY,
    work_order_id       TEXT NOT NULL,
    
	machine_id          INT NOT NULL,
    process_id    		INT NOT NULL,
	process_route_id	INT NOT NULL,
    step_number         INT NOT NULL,

	batch_id            INT GENERATED BY DEFAULT AS IDENTITY,
	
	process_start       NUMERIC NOT NULL,
    process_end         NUMERIC NOT NULL,

	ideal_cycle_time    INT NOT NULL,	
    actual_cycle_time   NUMERIC NOT NULL,
    
	event_status        TEXT NOT NULL,

	scenario_id			TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (event_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id),
		
	UNIQUE (batch_id, scenario_id)
);

CREATE TABLE fact_downtime_event (
    downtime_id         INT GENERATED BY DEFAULT AS IDENTITY,
    
	work_order_id 		TEXT NOT NULL,
	process_id			INT NOT NULL,
	process_route_id	INT NOT NULL,
	machine_id          INT NOT NULL,
    
	failure_type        TEXT NOT NULL,
    
	usage_duration      NUMERIC NOT NULL,
    failure_start       NUMERIC NOT NULL,
    failure_end         NUMERIC NOT NULL,

	scenario_id			TEXT NOT NULL,
	created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (downtime_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
);

CREATE TABLE fact_quality_event (
    quality_id          INT GENERATED BY DEFAULT AS IDENTITY,
    
	work_order_id       TEXT NOT NULL,
	machine_id          INT NOT NULL,
	process_id			INT NOT NULL,
    process_route_id    INT NOT NULL,
    step_number         INT NOT NULL,
	
	batch_id            INT NOT NULL,
    
	initial_quantity    BIGINT NOT NULL,
	units_approved      BIGINT NOT NULL,
    units_scrapped      BIGINT NOT NULL,

	event_time          NUMERIC NOT NULL,

	scenario_id			TEXT NOT NULL,
    created_at          TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (quality_id, scenario_id),

	FOREIGN KEY (work_order_id, scenario_id)
		REFERENCES fact_work_order(work_order_id, scenario_id),
	FOREIGN KEY (process_id, scenario_id)
		REFERENCES dim_process(process_id, scenario_id),
	FOREIGN KEY (process_route_id, scenario_id)
		REFERENCES dim_process_route(process_route_id, scenario_id),
	FOREIGN KEY (machine_id, scenario_id)
		REFERENCES dim_machine(machine_id, scenario_id),
	FOREIGN KEY (scenario_id)
		REFERENCES dim_scenario(scenario_id)
	-- Future extension: defect_type, severity
);
--
CREATE INDEX idx_fpe_keys
ON staging.fact_production_event
(work_order_id, process_route_id, machine_id, scenario_id);

CREATE INDEX idx_fdp_keys
ON staging.fact_downtime_event
(work_order_id, process_route_id, machine_id, scenario_id);

CREATE INDEX idx_fqe_keys
ON staging.fact_quality_event
(work_order_id, batch_id, scenario_id);

CREATE INDEX idx_fpe_scenario
ON staging.fact_production_event (scenario_id);

CREATE INDEX idx_fdp_scenario
ON staging.fact_downtime_event (scenario_id);

CREATE INDEX idx_fqe_scenario
ON staging.fact_quality_event (scenario_id);

CREATE INDEX idx_fdp_scenario_keys
ON staging.fact_downtime_event
(scenario_id, work_order_id, process_route_id, machine_id);

CREATE INDEX idx_fqe_scenario_keys
ON staging.fact_quality_event
(scenario_id, work_order_id, batch_id);

